name: Set up bun
description: Set up bun environment and install dependencies

runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@b7a1c7ccf290d58743029c4f6903da283811b979 # v2.1.0
      with:
        bun-version-file: .tool-versions

    - name: Bun Install
      shell: bash
      run: bun i --frozen-lockfile --ignore-scripts
